---
workshops:
  common:
    ports:
      - proto: 47
        to_port: -1
        from_port: -1
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 443
        from_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: icmp
        to_port: -1
        from_port: -1
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 80
        from_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 22
        from_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 8000
        from_port: 8000
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 8080
        from_port: 8080
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 8081
        from_port: 8081
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 8443
        from_port: 8443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 5432
        from_port: 5432
        cidr_ip: 172.16.0.0/14
        rule_desc: Cluster option DB port
      - proto: tcp
        to_port: 4444
        from_port: 4444
        cidr_ip: 0.0.0.0/0
        rule_desc: Metasploit reverse-shell
  